# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Programming Club IIT Kanpur
email: pclubiitk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Programming Club, IIT Kanpur
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pclub.in" # the base hostname & protocol for your site
twitter_username: pclubiitk
github_username:  pclubiitk
facebook_username:  pclubiitk
disqus_id: 

excoordies:
  '2017 - 18':
    'Arjun Sinha':
      mail: arjuns@iitk.ac.in
      github: ajs97
      image: arjun.jpg
      body: |
          Interning at Tower Research in Summer 2018.
          ACM ICPC World Finalist.
    'Milind Luthra':
      mail: milindl@iitk.ac.in
      github: milindl
      image: milind.jpg
      body: |
          Interning at Flipkart, Bangalore in Summer 2018.
    'Varun Khare':
      mail: varun@iitk.ac.in
      github: varunkhare1234
      image: varun.png
      body: |
          Research Intern at National University of Singapore in Summer 2018.
    'Yash Srivastav':
      mail: yashsriv@iitk.ac.in
      github: yashsriv
      image: yash.jpg
      body: |
          Research Intern at New York University in Summer 2018.
          Successfully completed GSoC in 2017 under the Linux Foundation.
  '2016 - 17':
    'Kunal Kapila':
      mail: kunalapila@gmail.com
      github: kunalapila
      image: kunal.jpg
      body: |
        PPO at Tower Research.
        Interned at Tower Research in Summer 2017.
        Chairperson Students&#39; Senate 2017-18.
    'Pallav Agarwal':
      mail: pallavagarwal07@gmail.com
      github: pallavagarwal07
      image: pallav.jpg
      body: |
        Joining Google, India.
        Interned at Google, NYC in Summer 2017. Successfully
        completed GSoC in 2016 under the Gentoo Foundation.
    'Saksham Sharma':
      mail: saksham0808@gmail.com
      github: sakshamsharma
      image: saksham.jpg
      body: |
        Joining Tower Research, NYC.
        Interned at Google, Seattle in Summer 2017. Has been a
        research fellow at Max Planck Institute for Software System.
    'Vinayak Tantia':
      mail: tantia.vinayak1@gmail.com
      github: vtantia
      image: vinayak.jpg
      body: |
        Joining Facebook AI Research, Canada.
        Interned at MILA, Canada in Spring 2018 and at Google, India in Summer 2017.


# Gems
gems: 
- jekyll-archives
- jekyll-paginate

# Config
paginate: 5
paginate_path: "page/:num"
# Build settings
markdown: kramdown
# Exclude dirs
exclude: [vendor]

# Archive
jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

# Kramdown
kramdown:
  input: GFM
  hard_wrap: false

cloudsh_token: "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMWVhZGI4NWItMDgwNS00MDRkLWJhYmMtOGQ5Mjc5OGYzNDliIiwiaW5kZXhfaWQiOiIyMzk3Yjk4Yy1lMTk3LTRjMGQtOTlkYS04NGIxOWEzMjk1ZjEiLCJpbmRleF91cmwiOiJodHRwOi8vcGNsdWIuaW4ifQ.49yI9ac98bXkeoIzXxW_LRA_tTJgHeAErr_aVgu1MQg"
